import random
import datetime

# ── Configuration ──
ZONES = [
    "Centre Ville", "Medina de Sousse", "Bab Bhar", "Grande Mosquee", "Ribat de Sousse", 
    "Kasbah", "Souk Erbaa", "Port de Sousse", "Corniche", "Boujaafar", "Sahloul 1", 
    "Sahloul 2", "Sahloul 3", "Khzema Est", "Khzema Ouest", "Hammam Sousse", 
    "Port El Kantaoui", "Kantaoui Marina", "Akouda", "Chott Meriem", "Hergla", 
    "Sousse Riadh", "Ezzouhour", "Bouhsina", "Jawhara", "Sidi Abdelhamid", 
    "Cite Olympique", "Route Touristique", "Zone Industrielle Sidi Abdelhamid", 
    "Kalaa Kebira", "Kalaa Seghira", "Msaken"
]

INDUSTRIAL_ZONES = ["Route Touristique", "Port de Sousse", "Zone Industrielle Sidi Abdelhamid"]

CAPTEUR_TYPES = [
    "pollution", "co2", "temperature", "humidite", "trafic", "bruit", 
    "eclairage", "parking", "dechet", "energie"
]

CAPTEUR_STATUSES = ["ACTIF", "INACTIF", "SIGNALE", "EN_MAINTENANCE", "HORS_SERVICE"]

VEHICLE_TYPES = ["bus", "voiture", "camion", "moto", "ambulance", "police", "maintenance"]
VEHICLE_STATUSES = ["EN_ROUTE", "STATIONNE", "EN_PANNE", "ARRIVE"]

INTERVENTION_STATUSES = ["DEMANDE", "TECH1_ASSIGNE", "TECH2_VALIDE", "IA_VALIDE", "TERMINE"]

FIRST_NAMES = ["Amine", "Salma", "Yassine", "Leila", "Mohamed", "Sonia", "Karim", "Olfa", "Walid", "Hana", "Anis", "Mariem", "Hamza", "Ines", "Mehdi", "Zied", "Rim", "Faten", "Sami", "Nadia"]
LAST_NAMES = ["Ben Ahmed", "Trabelsi", "Dridi", "Gharbi", "Belhadj", "Mansour", "Jlassi", "Saidi", "Brahmi", "Chaabane", "Karray", "Abid", "Mnif", "Smaoui", "Zghal", "Rekik", "Feki", "Louati", "Ellouze", "Hachicha"]

def generate_sql():
    sql = []
    sql.append("-- ───────────────────────────────────────────────────────────")
    sql.append("-- SEED SOUSSE HUGE — Smart City Neo-Sousse 2030")
    sql.append("-- Generated by Antigravity AI")
    sql.append("-- ───────────────────────────────────────────────────────────\n")

    sql.append("TRUNCATE TABLE mesures, interventions, vehicules, citoyens, capteurs RESTART IDENTITY CASCADE;\n")

    # 1. CITOYENS (500)
    sql.append("-- 1. CITOYENS")
    citoyen_values = []
    for _ in range(500):
        nom = f"{random.choice(FIRST_NAMES)} {random.choice(LAST_NAMES)}".replace("'", "''")
        score = random.randint(30, 98)
        adresse = f"{random.choice(ZONES)}, Sousse".replace("'", "''")
        citoyen_values.append(f"('{nom}', {score}, '{adresse}')")
    
    for i in range(0, len(citoyen_values), 100):
        sql.append(f"INSERT INTO citoyens (nom, score_ecolo, adresse) VALUES \n" + ",\n".join(citoyen_values[i:i+100]) + ";")
    sql.append("\n")

    # 2. CAPTEURS (100)
    sql.append("-- 2. CAPTEURS")
    capteur_values = []
    capteurs_data = [] 
    for i in range(1, 101):
        ctype = random.choice(CAPTEUR_TYPES)
        zone = random.choice(ZONES)
        statut = random.choices(CAPTEUR_STATUSES, weights=[70, 5, 10, 10, 5])[0]
        date_inst = (datetime.datetime.now() - datetime.timedelta(days=random.randint(30, 365))).date()
        capteur_values.append(f"('{ctype}', '{zone}', '{statut}', '{date_inst}')")
        capteurs_data.append({"id": i, "type": ctype, "zone": zone, "statut": statut})
    
    for i in range(0, len(capteur_values), 100):
        sql.append(f"INSERT INTO capteurs (type, zone, statut, date_installation) VALUES \n" + ",\n".join(capteur_values[i:i+100]) + ";")
    sql.append("\n")

    # 3. VÉHICULES (150)
    sql.append("-- 3. VÉHICULES")
    vehicle_values = []
    for _ in range(150):
        vtype = random.choice(VEHICLE_TYPES)
        trajet = random.randint(1, 20)
        statut = random.choice(VEHICLE_STATUSES)
        vehicle_values.append(f"('{vtype}', {trajet}, '{statut}')")
    
    for i in range(0, len(vehicle_values), 50):
        sql.append(f"INSERT INTO vehicules (type, trajet_id, statut) VALUES \n" + ",\n".join(vehicle_values[i:i+50]) + ";")
    sql.append("\n")

    # 4. INTERVENTIONS (200)
    sql.append("-- 4. INTERVENTIONS")
    intervention_values = []
    for _ in range(200):
        cap_id = random.randint(1, 100)
        tech1 = random.randint(1, 20)
        tech2 = random.randint(21, 40) if random.random() > 0.5 else "NULL"
        statut = random.choice(INTERVENTION_STATUSES)
        date = datetime.datetime.now() - datetime.timedelta(days=random.randint(1, 15), hours=random.randint(0, 23))
        intervention_values.append(f"({cap_id}, {tech1}, {tech2}, '{statut}', '{date}')")
    
    for i in range(0, len(intervention_values), 50):
        sql.append(f"INSERT INTO interventions (capteur_id, technicien1_id, technicien2_id, statut, date) VALUES \n" + ",\n".join(intervention_values[i:i+50]) + ";")
    sql.append("\n")

    # 5. MESURES (20,000)
    sql.append("-- 5. MESURES")
    mesure_values = []
    actifs = [c for c in capteurs_data if c["statut"] == "ACTIF"]
    if not actifs: actifs = capteurs_data
    
    now = datetime.datetime.now()
    for _ in range(20000):
        cap = random.choice(actifs)
        ctype = cap["type"]
        zone = cap["zone"]
        
        if ctype == "pollution":
            base = 60 if zone in INDUSTRIAL_ZONES else 20
            val = base + random.uniform(0, 80)
        elif ctype == "co2":
            base = 600 if zone in INDUSTRIAL_ZONES else 350
            val = base + random.uniform(0, 600)
        elif ctype == "temperature":
            val = 18 + random.uniform(0, 15)
        elif ctype == "humidite":
            val = 40 + random.uniform(0, 50)
        elif ctype == "trafic":
            val = random.uniform(0, 100)
        elif ctype == "bruit":
            val = 40 + random.uniform(0, 60)
        else:
            val = random.uniform(0, 100)
            
        timestamp = now - datetime.timedelta(days=random.randint(0, 29), hours=random.randint(0, 23), minutes=random.randint(0, 59))
        mesure_values.append(f"({cap['id']}, '{ctype}', {round(val, 2)}, '{timestamp}')")

    for i in range(0, len(mesure_values), 500):
        sql.append(f"INSERT INTO mesures (capteur_id, type_mesure, valeur, date) VALUES \n" + ",\n".join(mesure_values[i:i+500]) + ";")
    
    output_path = "../bdd/seed_sousse_huge.sql"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sql))
    print(f"File generated: {output_path}")

if __name__ == "__main__":
    generate_sql()
